### ISSUE TITLE
How to train with my own data with point supervision and my own model, not fcn32 model?

### ISSUE THREAD

**Issue by brisker** [abearman/whats-the-point1#1]
I mean I can only find three .prototxt files in the folder and I can not find the new soft_max_expectation layer in the the three.  I do not quite understand where to see the difference between point supervision and pixel-level supervision from the files. 
![image](https://cloud.githubusercontent.com/assets/13804492/18409650/445cd794-777f-11e6-999c-eefc437e2639.png)

**Comment by abearman** [comment]
Hi @brisker, the general FCN-32s .prototxt files are in the [FCN-32s models directory](https://github.com/abearman/whats-the-point1/tree/master/caffe/models/fcn-32s-pascal). The prototxt files you find in the main code directory unfortunately are not relevant and I should probably remove them. 

These three general .prototxt files are copied and modified by the [solve.py](https://github.com/abearman/whats-the-point1/blob/master/whats-the-point-2016/code/solve.py) script for each of the models found [here](https://github.com/abearman/whats-the-point1/tree/master/caffe/models/fcn-32s-pascal/2012). For example, you'll notice that the point-supervised, SoftmaxWithLossExpectation layer is used for [this specific model](https://github.com/abearman/whats-the-point1/blob/master/caffe/models/fcn-32s-pascal/2012/real1-click1-cls-con/train_val.prototxt) but not in the general case, which uses the pixel-level supervised SoftmaxWithLoss. 

I hope this helps!
